# Generated by Django 6.0.6 on 2026-07-13 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_user_desc_user_title_alter_user_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='desc',
            new_name='bio',
        ),
    ]
